### ISSUE TITLE
И где взять эти "String appId, String scope" - просто по логину и паролю нельзя?

### ISSUE THREAD

**Issue by anonym24** [DruidKuma/vk-access-token-getter#1]
И где взять эти "String appId, String scope" - просто по логину и паролю нельзя?

**Comment by DruidKuma** [comment]
Именно access token просто по логину и паролю нельзя - токен использует ID приложения разработчика для идентификации.
По сути, можно залогиниться и получить cookie авторизации, но для вызова VK API этого недостаточно.  App ID можно получить, создав за минуту свое вк приложение через портал разработчиков (https://vk.com/dev, линк "Мои приложения" в меню, "Создать приложение"). Там же, из документации можно посмотреть доступные scopes.
